### ISSUE TITLE
Highlights are not visible on elements with `background-color`

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [recogito/text-annotator-js#36]
## Issue
I noticed that the highlight rendered on `canvas` is not visible on elements that have any `background-color` 👁️👁️👁️

https://github.com/recogito/text-annotator-js/assets/68850090/6190cddf-e264-4e6f-9cb7-05777fc25aac

The issue is easily reproducible even when running the build-in example page

**Comment by rsimon** [comment]
Yes, good point. This is pretty much impossible to fix with the current rendering approach. I'll leave this issue open, but it's more or less a case of "won't fix". HOWEVER... the CSS Custom Highlight-based renderer will handle this case just fine. So once that arrives, we can think about closing the issue.

(FWIW: I also have ideas for a different "legacy-support" mode which would work more along the lines of the old RecogitoJS, inserting SPANs into the DOM. But that would take more work and isn't currently on the immediate roadmap.)

**Comment by rsimon** [comment]
If you are interested in a hacked workaround: as you know, the highlight is rendered on a transparent canvas behind the text. (This is because it won't fade the text color.) You could use CSS `z-index` to move it before the text. This will make the text fade somewhat, but at least the highlight will be visible regardless of the text background.

**Comment by oleksandr-danylchenko** [comment]
> This is pretty much impossible to fix with the current rendering approach. I'll leave this issue open, but it's more or less a case of "won't fix"

That's super unfortunate ☠️
Because we won't be able adopt the Highlight API for quite some time. Also inserting SPANs has already bitten us in the past. As React doesn't like the DOM mutations that are out of sync with its internal state and could randomly throw exceptions for our user. That's why we bought into the canvas-based approach 😅

**Comment by oleksandr-danylchenko** [comment]
Oh... That was a surprisingly easy "fix" 👁️👁️👁️

![image](https://github.com/recogito/text-annotator-js/assets/68850090/47176d87-5537-4a90-b212-7cf2a2b1137c)
<img width="1574" alt="image" src="https://github.com/recogito/text-annotator-js/assets/68850090/d6726590-a1ca-438a-a582-051a3a674ac0">

**Comment by oleksandr-danylchenko** [comment]
Tested it a bit, and it seems to work okay...
But I expect that it must shoot me in a knee somehow...

**Comment by oleksandr-danylchenko** [comment]
Also, I'm not sure why the canvases were separated in the 1st place 🤔 
They appear to have the same size, they have the same lifecycle... The only difference is that the `fgCanvas` is `highres`: https://github.com/recogito/text-annotator-js/blob/480669730240e2ee4ac09f4afea0faf173c47faf/packages/text-annotator/src/highlight/highlightLayer.ts#L52-L53

Even considering that, the `fgCanvas` was _used exclusively_ to obtain the size of the painting rect and it wasn't used for actual painting: https://github.com/recogito/text-annotator-js/blob/480669730240e2ee4ac09f4afea0faf173c47faf/packages/text-annotator/src/highlight/highlightLayer.ts#L102

**Comment by oleksandr-danylchenko** [comment]
Ah... I suppose it'll conflict with the `PresencePainter` that uses both the `bg` and `fg` canvases 🤔 

https://github.com/recogito/text-annotator-js/blob/480669730240e2ee4ac09f4afea0faf173c47faf/packages/text-annotator/src/presence/PresencePainter.ts#L59-L63

**Comment by rsimon** [comment]
Hi, yes I was just about to answer: the fg canvas is used exclusively by the presence layer. We use this to render GoogleDocs like collaborator overlays. See below.

<img width="800" alt="Bildschirmfoto 2024-02-16 um 16 41 44" src="https://github.com/recogito/text-annotator-js/assets/470971/fc3945b6-c171-49d4-964f-391e979be44f">

Bit of a legacy artefact, really. Initially I felt we might have different painters at some point, possibly as plugins, which might want to render things with different styles and need either back- and foreground, which is why I left both canvases in.

That being said: I'm about to re-organize this now, anyway. Because the whole "Painter" concept doesn't really work with CSS Highlighters. Not 100% how I'll reorganize it yet. But the presence layer will definitely change, and instantiate it's own Canvas element. 

P.S.: just to explain the reason for the double resolution on the fg layer. Also an artefact of our own, single use of the foreground layer. Without boosting resolution up by 2, you don't get Retina resolution. Text, in particular, comes out blurry (not just on Mac).

**Comment by rsimon** [comment]
P.P.S.: I think it would actually safe to paint to the fg layer yourself. The presence painter would add to it. But there should be no interference as such.

**Comment by oleksandr-danylchenko** [comment]
So it would like this: 
<img width="633" alt="image" src="https://github.com/recogito/text-annotator-js/assets/68850090/de7463bc-5db0-4a2d-8af3-a4417cf950ae">

But in that case the `style` and the `painter` props should be mutually exclusive. Because when the `painter` is present - the `style` just won't be used 🤷🏻‍♂️

**Comment by rsimon** [comment]
Perhaps hold off until I have spent some thought about how to re-organize the whole highlighter/painter architecture. I don't expect huge changes. But things will definitely mess up PRs created before the re-organization. (The good news is I'll be working on this - probably - a bit over the weekend already and - definitely - most of Monday.)

**Comment by rsimon** [comment]
Yes - I'd see the painter essentially as a behavior-changing plugin or something. It's up to the painter whether it does something with the style, or whether it chooses to ignore it.

**Comment by oleksandr-danylchenko** [comment]
>  (The good news is I'll be working on this - probably - a bit over the weekend already and - definitely - most of Monday.)

Sounds great! 🚀  
Luckily it doesn't block us that much and it was useful to discover how this issue be worked around 👌🏻

**Comment by rsimon** [comment]
I'll also try to read through your code for the not-annotatable regions over the weekend. I think I get the basic idea, and agree with all of your conclusions. (In particular that it's too costly to recompute the ranges on the fly when reviving.) It's a useful extension which I believe might sooner or later come as a requirement from our clients, too.

**Comment by oleksandr-danylchenko** [comment]
@rsimon, hello 👋🏻 
I saw your new PR for the Highlight API feature and looks pretty good 👍🏻 

But now I'm confused by the meaning and separation of the "painter" and the "renderer"... 

Let's take the `highlightRenderer` as an example. Previosly, there were separate `highlightLayer` that was extracting state and rects to render and `highlightPainter` that was painting them. So in the message above I was able to fix missing highlights on elements with background by _overriding the painger_. 
But now there's no such separation... 🤔. `highlightRenderer` also pains the rects on its canvas. And by that, I'm no longer able to override just the painter and use the foreground canvas instead of the background ;(

And then let's look at the `PresencePainter` that also extracts data from the state and paints on its own canvas alongside the highlights from the `highlightRenderer`.

---

So the questions are:
- Shouldn't the highlight painter be separated from the `highlightRenderer`? It'll make it possible to avoid default highlight rendering. Especially in the case where only need a canvas that _will be rendered above the elements with the background_.
- I think that the names `painter` and `renderer` are pretty close synonyms, which makes it harder to grasp the separation. I preferred the `highlightLayer` more

**Comment by rsimon** [comment]
Yes, I had to change the setup for the following reason:

- When using CSS Custom Highlight, part of the "painting" is just a CSS rule. 
- The presence overlays, on the other hand, still require a Canvas

Therefore, the renderer is now fully responsible for drawing the highlights (either on a background canvas, or via CSS). The "painter", for lack of a better name, gets called by the renderer. When it gets called, it can perform whatever side effect it needs to perform (like drawing presence overlays), and can return a HighlightStyle which the renderer will then use.

We could think about a flag that puts the canvas in front of the text. Or, otherwise, you can simply move it in front via CSS `z-index`. The old way of overriding the paint process will no longer be supported. Simply because there is no more single paint process. (But it's either Canvas or CSS Highlights.)

**Comment by oleksandr-danylchenko** [comment]
Thanks for the clarification! I looked through the code a few more times and I think it finally starts to make sense, including using the custom painters as a side-effect. The only thing which is might be confusing along the road and for others is the fact that the custom painter won't _replace_ the renderer, but will be used as a _hook_ 🤔

**Comment by oleksandr-danylchenko** [comment]
Closing this issue as using `z-index` to reposition the `bg` canvas should be enough to handle the problematic highlighting on elements with the `background-color`

**Comment by oleksandr-danylchenko** [comment]
Ugh... I found that just applying the `z-index` to the `bg` canvas
https://github.com/recogito/text-annotator-js/blob/3a70b9ef5cafec4b54ed629e934e5875d6f06262/packages/text-annotator/src/highlight/canvas/highlightRenderer.ts#L9-L15
isn't the best solution in combination with the `SelectionHander` that creates annos on the `selectionchange` event:
https://github.com/recogito/text-annotator-js/blob/3a70b9ef5cafec4b54ed629e934e5875d6f06262/packages/text-annotator/src/SelectionHandler.ts#L73-L84

It makes the text a user selects look too pale
![image](https://github.com/recogito/text-annotator-js/assets/68850090/ab4e2fd5-a473-4af2-9a9d-091c30092287)
because the canvas already renders the highlight over it

**Comment by rsimon** [comment]
Yes, that's the caveat... inherent limitation of the canvas-based approach. Another reason for why I've been looking forward to the Custom CSS Highlights so much. And also why I've kept considering the "old" Span-insertion approach as a possible legacy fallback. (Despite all the problems it causes...)

**Comment by oleksandr-danylchenko** [comment]
I suppose that its impact can be minimized by at least creating the annos not on the selection, but on pointerup. So the highlight layer won't interfere with the browser's selection indication

**Comment by rsimon** [comment]
Would that make such a difference? Yes, it would look better during selection - but as soon as you mouse-up, the annotation gets rendered, and the text will pale :-(

**Comment by rsimon** [comment]
Hm, yes, agreed. I guess it depends on how you set your transparency. When selecting, it's probably two effects overlapping each other.

**Comment by oleksandr-danylchenko** [comment]
Playing with opacity was the actual key!
![image](https://github.com/recogito/text-annotator-js/assets/68850090/89a124c0-967c-4a9d-b755-92b9626d95d6)

https://github.com/recogito/text-annotator-js/assets/68850090/69f78cf9-5b00-4853-9481-10769b9bbab3

**Comment by rsimon** [comment]
Looks good! Re Safari 17.2... time will be on our side ;-)

**Comment by rsimon** [comment]
Just a quick ping on this, since I've run into the same problem in a different context: especially with the new SPAN-based renderer, I had some good success by:
- using CSS `z-index` to place the highlight layer in front of the text
- use CSS `mix-blend-mode` to blend the color with the underlying content

For white/bright background, `mix-blend-mode: multiply` will often give you the right results. The color transfers to the background, the text remains dark. For dark background, `mix-blend-mode: overlay` works well. 

It's not a one-size-fits-all solution, and depends strongly on background and text color. But can give you good results if you are in control of the text content style.

**Comment by oleksandr-danylchenko** [comment]
Thanks for the insight! 🙌🏻 
I haven't tried applying the blend mode for the canvas highlights yet. Just using the `z-index` with tuned colors worked decently well too. But I'll give it a try and see if it makes the "tuning" easier
